### ISSUE TITLE
ContentList Persistance

### ISSUE THREAD

**Issue by cmontalban** [daisy/DAISY-Online-Refresh#92]
What is the lifetime of a ContentList generated by GetQuestions
i.e. Can L100 be destroyed when L200 is generated or do we need to hold multiple Lists active for the lifetime of the Session?

The DODP Spec says:
Services should persist contentList identifiers for the duration of a Session. Services must not expose multiple contentLists with the same arbitrary identifier during the same session.

I cannot see why this is necessary but this means the list of ContentItems for each ContentListRef will need to be written to the DB under a CustomId
A single Search can return thousands of items (a relevancy search)
It would be much easier if any device could only have 1 active list at any 1 time - Do not see the downsides with this.

In what use-case is a user requiring access to multiple lists?

This would also mean the Search string that produces the list could be stored against the Id generating the result each time rather than persisting it.
This would mean the results are always current and the search interface could be used to support paging.

Suggestion: Implement rule that only 1 ContentList may exist at any given time for a Device

**Comment by bvanvelsen** [comment]
I actually don't see a need why the DODP should manage how many lists a server can or should handle for a given device? Usually a search is quite a performance/memory intensive action for a server. So caching search results for mulitple devices/users/sessions can be useful. And why shouldn't the server be allowed to re-use exising contentlistRef's? If the server chooses to do this? a reading device doesn't have knowledge about contentlistRef's that are being re-used by other users/sessions.

<b>In what use-case is a user requiring access to multiple lists?</b>
A possible scenario could be a smartphone/tablet again. Imagine a user doing a search, and the backend returns a paginated list where results a returned 10 items at a time. Suppose the user queried item 30 to 40, and then decides to query a different search, yielding another 1000 results. If the user then switches back again to the first search result, it would be nice to know that a reading device can re-use the contentListRef it knows from a previous search, instead of going through the entire search process again, triggering more server load and request/responses(mobile data traffic, bandwidth limitations, battery consumptions, etc...). Obviously assuming that contentListRefs stay active for the duration of a session.

**Comment by cmontalban** [comment]
Services are required to make available the most recent contentListRef to a device within a given Session.   This allows the device to access the list once the search has been completed until logoff or another search is performed.

**Comment by giltay** [comment]
Note the word "should". This, per RFC 2119, means it is a recommendation, not a requirement.

**Comment by cmontalban** [comment]
Resolved in issue #96
